spring:
  datasource:
    url: jdbc:mysql://localhost:3306/logs?rewriteBatchedStatements=true
    username: root
    password: rootpassword

spring.jpa.properties.hibernate.jdbc.batch_size: 100
spring.jpa.properties.hibernate.order_inserts: true
spring.jpa.properties.hibernate.order_updates: true
